"""Optional FLAC3D command-file (.dat) skeleton generator.

Emits a *generic* starting script that imports the grid and stubs out a
constitutive model assignment per zone group and a boundary condition per face
group. It contains no project-specific parameters — the user fills those in.
"""

from __future__ import annotations

import os


def write_dat_skeleton(path, f3grid_path, grid):
    grid_name = os.path.basename(f3grid_path)
    with open(path, "w", encoding="utf-8") as f:
        f.write("; FLAC3D command skeleton generated by mesh2flac3d\n")
        f.write("; Fill in constitutive models, properties and BC values.\n\n")
        f.write("model new\n")
        f.write("model large-strain off\n")
        f.write(f"zone import '{grid_name}'\n\n")

        f.write("; --- Constitutive model per zone group ---\n")
        if grid.zone_groups:
            for name in grid.zone_groups:
                f.write(f"zone cmodel assign elastic range group '{name}'\n")
                f.write(f"; zone property young 1e9 poisson 0.3 range group '{name}'\n")
        else:
            f.write("; (no zone groups found)\n")
        f.write("\n")

        f.write("; --- Boundary conditions per face group ---\n")
        if grid.face_groups:
            for name in grid.face_groups:
                f.write(f"; zone face apply velocity-normal 0 range group '{name}'\n")
        else:
            f.write("; (no face groups found)\n")
        f.write("\n")

        f.write("; model gravity 0 0 -9.81\n")
        f.write("; model solve\n")
